# Site settings
title: Marcin 'vi4m' Kliks blog
email: spamlist@icloud.com
description: "Creating things is the one that makes human so special. Once you start creating things, there is no back. "
baseurl: "http://vi4m.github.io"
url: "http://marcinkliks.pl"

# Build settings
markdown: kramdown
permalink: pretty
