# Site settings
title: Software Craftmanship made sexy
email: spamlist@icloud.com
description: "How to make performant, usable and sexy software using Python"
baseurl: "http://vi4m.github.io"
url: "http://marcinkliks.pl"
highlighter: pygments
is_user_page: true



# Build settings
markdown: kramdown
permalink: pretty


author :
  name : Marcin Kliks
  email : spamlist@icloud.com
  github : vi4m
  twitter : vi4m
  linkedin: marcin.kliks
  stackoverflow: vi4m
